services:
  mysql:
    container_name: mysql_movieVerse_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movieVerse_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - movieVerse-net
    restart: unless-stopped

  mail-dev:
    container_name: maildev_movieVerse_container
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  movieVerse-net:
    driver: bridge

volumes:
  mysql_data:
