services:
  mysql:
    container_name: mysql_movieVerse
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movieVerse_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - movieVerse-net
    restart: unless-stopped

networks:
  movieVerse-net:
    driver: bridge

volumes:
  mysql_data: